export default {
  name: 'Имя',
  save: 'Сохранить',
  saveAs: 'Сохранить как',
  back: 'Назад',
  loading: 'Загрузка...',
  resetOperations: 'Отменить все операции',
  changesLoseConfirmation: 'Все изменения будут потеряны',
  changesLoseConfirmationHint: 'Вы уверены, что хотите продолжить',
  cancel: 'Закрыть',
  continue: 'Продолжить',
  undoTitle: 'Отменить последнее изменение',
  redoTitle: 'Повторить последнее изменение',
  showImageTitle: 'Показать оригинальное изображение',
  zoomInTitle: 'Увеличить',
  zoomOutTitle: 'Уменьшить',
  toggleZoomMenuTitle: 'Изменить зум',
  adjustTab: 'Обрезать',
  finetuneTab: 'Finetune',
  filtersTab: 'Фильтры',
  watermarkTab: 'Водяной знак',
  annotateTab: 'Изменить',
  resize: 'Изменить размер',
  resizeTab: 'Изменить размер',
  invalidImageError: 'Недопустимое изображение',
  uploadImageError: 'Ошибка при загрузке изображения',
  areNotImages: 'не является изображением',
  isNotImage: 'не является изображением',
  toBeUploaded: 'должно быть загружено',
  cropTool: 'Обрезать',
  original: 'Оригинал',
  custom: 'Свое',
  square: 'Квадрат',
  landscape: 'Пейзаж',
  portrait: 'Портрет',
  ellipse: 'Эллипс',
  classicTv: 'Классическое ТВ',
  cinemascope: 'Синемаскоп',
  arrowTool: 'Стрелка',
  blurTool: 'Размытие',
  brightnessTool: 'Яркость',
  contrastTool: 'Контрастность',
  ellipseTool: 'Эллипс',
  unFlipX: 'Перевернуть по X',
  flipX: 'Перевернуть по X',
  unFlipY: 'Перевернуть по Y',
  flipY: 'Перевернуть по Y',
  hsvTool: 'HSV',
  hue: 'Hue',
  saturation: 'Насыщенность',
  value: 'Значение',
  imageTool: 'Изображение',
  importing: 'Импортирование...',
  addImage: '+ Добавить изображение',
  uploadImage: 'Загрузить изображение',
  fromGallery: 'Из галереи',
  lineTool: 'Линия',
  penTool: 'Перо',
  polygonTool: 'Полигон',
  sides: 'Стороны',
  rectangleTool: 'Прямоугольник',
  cornerRadius: 'Радиус угла',
  resizeWidthTitle: 'Ширина в пикселях',
  resizeHeightTitle: 'Высота в пикселях',
  toggleRatioLockTitle: 'Переключить блокировку соотношения',
  reset: 'Сбросить',
  resetSize: 'Сбросить до исходного размера изображения',
  rotateTool: 'Повернуть',
  textTool: 'Текст',
  textSpacings: 'Расстояния между текстами',
  textAlignment: 'Выравнивание текста',
  fontFamily: 'Семейство шрифтов',
  size: 'Размер',
  letterSpacing: 'Расстояние между буквами',
  lineHeight: 'Высота строки',
  warmthTool: 'Теплота',
  addWatermark: '+ Добавить водяной знак',
  addWatermarkTitle: 'Выберите тип водяного знака',
  uploadWatermark: 'Загрузить водяной знак',
  addWatermarkAsText: 'Добавить как текст',
  padding: 'Отступ',
  shadow: 'Тень',
  horizontal: 'Горизонтальный',
  vertical: 'Вертикальный',
  blur: 'Размытие',
  opacity: 'Прозрачность',
  position: 'Положение',
  stroke: 'Обводка',
  saveAsModalLabel: 'Сохранить изображение как',
  extension: 'Расширение',
  nameIsRequired: 'Имя обязательно',
  quality: 'Качество',
  imageDimensionsHoverTitle: 'Размер сохраненного изображения (ширина x высота)',
  cropSizeLowerThanResizedWarning: 'Примечание, выбранная область кадрирования меньше, чем примененный размер, что может привести к снижению качества',
  actualSize: 'Базовый зум (100%)',
  fitSize: 'Полный размер',
  addImageTitle: 'Выберите изображение для добавления...',
};
